import { useMemo, useState } from 'react'
import { Play, RotateCcw, Zap } from 'lucide-react'
import { markProgress } from '../../progress'
import { clamp, entropy, hashNoise, pct, softmax } from './math'

export function TransformerBlockLab({ nodeId }: { nodeId?: string }) {
  const [norm, setNorm] = useState<'Pre-LN' | 'Post-LN'>('Pre-LN'); const [residual, setResidual] = useState(true); const [tokens, setTokens] = useState(128); const [width, setWidth] = useState(512); const [ffn, setFfn] = useState(2048); const [ran, setRan] = useState(false)
  const estimate = useMemo(() => { const attention = 4 * tokens * tokens * width; const mlp = 4 * tokens * width * ffn; const params = 4 * width * width + 2 * width * ffn; const risk = clamp((norm === 'Post-LN' ? .35 : .08) + (!residual ? .5 : 0) + (width > 1400 ? .12 : 0), 0, 1); return { attention, mlp, params, risk } }, [norm, residual, tokens, width, ffn])
  return <div className='foundation-console two-col'><section className='control-panel'><h3>Block 配置</h3><label>Norm<select value={norm} onChange={(event) => { setNorm(event.target.value as typeof norm); setRan(false) }}><option>Pre-LN</option><option>Post-LN</option></select></label><label className='toggle-row'><input type='checkbox' checked={residual} onChange={(event) => { setResidual(event.target.checked); setRan(false) }} />开启残差</label><label>Tokens <b>{tokens}</b><input type='range' min='16' max='1024' step='16' value={tokens} onChange={(event) => { setTokens(Number(event.target.value)); setRan(false) }} /></label><label>Attention 宽度 d <b>{width}</b><input type='range' min='128' max='2048' step='128' value={width} onChange={(event) => { setWidth(Number(event.target.value)); setRan(false) }} /></label><label>MLP 宽度 d_ff <b>{ffn}</b><input type='range' min='256' max='8192' step='256' value={ffn} onChange={(event) => { setFfn(Number(event.target.value)); setRan(false) }} /></label><div className='console-actions'><button onClick={() => { setRan(true); if (nodeId) markProgress(nodeId, 3) }}><Play />运行估算</button><button className='secondary' onClick={() => { setNorm('Pre-LN'); setResidual(true); setTokens(128); setWidth(512); setFfn(2048); setRan(false) }}><RotateCcw />重置</button></div></section><section className='output-panel'><div className='block-diagram'><div><span>Tokens</span><b>{ran ? `[${tokens}, ${width}]` : '[T, d]'}</b></div><strong>→ {norm}</strong><div className='attention-block'><span>Attention</span><b>token mixing</b></div><strong>＋ residual</strong><div className='mlp-block'><span>MLP</span><b>channel mixing</b></div></div><div className='metric-row-foundation'><div><span>参数量估算</span><b>{ran ? `${(estimate.params / 1e6).toFixed(1)}M` : '—'}</b></div><div><span>Attention FLOPs</span><b>{ran ? `${(estimate.attention / 1e9).toFixed(2)}G` : '—'}</b></div><div><span>MLP FLOPs</span><b>{ran ? `${(estimate.mlp / 1e9).toFixed(2)}G` : '—'}</b></div><div><span>稳定性风险</span><b className={estimate.risk > .5 ? 'bad-text' : ''}>{ran ? pct(estimate.risk, 0) : '—'}</b></div></div><div className='diagnostic-callout'>{!residual ? '关闭残差会切断恒等信息通路，深层训练风险显著。' : norm === 'Post-LN' ? 'Post-LN 深层训练对初始化和学习率更敏感。' : 'Pre-LN 通常更稳；仍需结合分层 grad norm 与真实压测。'}</div></section></div>
}

export function MoERouterLab({ go, nodeId }: { go: (page: string, options?: Record<string, string>) => void; nodeId?: string }) {
  const [experts, setExperts] = useState(8); const [topK, setTopK] = useState(2); const [capacity, setCapacity] = useState(1.1); const [balance, setBalance] = useState(.05); const [tokens, setTokens] = useState(64); const [collapse, setCollapse] = useState(false); const [nonce, setNonce] = useState(0); const [ran, setRan] = useState(false)
  const result = useMemo(() => { const safeK = Math.min(topK, experts); const logits = Array.from({ length: experts }, (_, index) => collapse ? (index === 0 ? 8 : -2) : Math.sin(index * 1.7 + hashNoise(experts, safeK, capacity, balance, tokens, nonce)) - balance * index / experts); const probs = softmax(logits, Math.max(.35, 1 + balance)); const assignments = tokens * safeK; const maxPerExpert = Math.max(1, Math.ceil(capacity * assignments / experts)); const raw = probs.map((prob) => Math.round(prob * assignments)); const load = raw.map((value) => Math.min(value, maxPerExpert)); const overflow = Math.max(0, raw.reduce((sum, value) => sum + Math.max(0, value - maxPerExpert), 0)); return { safeK, probs, load, raw, overflow, routingEntropy: entropy(probs), maxPerExpert, activeRatio: safeK / experts, communication: assignments * (experts > 8 ? 1.4 : 1) } }, [experts, topK, capacity, balance, tokens, collapse, nonce])
  const run = () => { setRan(true); setNonce((old) => old + 1); if (nodeId) markProgress(nodeId, 3) }
  return <div className='foundation-console'><section className='moe-controls'><label>Expert 数 <b>{experts}</b><input type='range' min='2' max='16' value={experts} onChange={(event) => { const value = Number(event.target.value); setExperts(value); setTopK(Math.min(topK, value)); setRan(false) }} /></label><label>Top-k <b>{topK}</b><input type='range' min='1' max={Math.min(4, experts)} value={topK} onChange={(event) => { setTopK(Number(event.target.value)); setRan(false) }} /></label><label>Capacity factor <b>{capacity.toFixed(2)}</b><input type='range' min='.5' max='2' step='.05' value={capacity} onChange={(event) => { setCapacity(Number(event.target.value)); setRan(false) }} /></label><label>Load balance loss λ <b>{balance.toFixed(2)}</b><input type='range' min='0' max='.5' step='.01' value={balance} onChange={(event) => { setBalance(Number(event.target.value)); setRan(false) }} /></label><label>Token 批次 <b>{tokens}</b><input type='range' min='8' max='256' step='8' value={tokens} onChange={(event) => { setTokens(Number(event.target.value)); setRan(false) }} /></label><label className='toggle-row'><input type='checkbox' checked={collapse} onChange={(event) => { setCollapse(event.target.checked); setRan(false) }} />注入路由坍缩</label></section><div className='console-actions'><button onClick={run}><Zap />运行路由</button><button className='secondary' onClick={() => { setExperts(8); setTopK(2); setCapacity(1.1); setBalance(.05); setTokens(64); setCollapse(false); setRan(false); setNonce(0) }}><RotateCcw />重置</button><button className='secondary' onClick={() => go('distill-course', { module: 'moe-and-stack' })}>MoE → Dense 蒸馏</button></div><div className='metric-row-foundation'><div><span>Overflow / Drop</span><b className={result.overflow ? 'bad-text' : ''}>{ran ? result.overflow : '—'}</b></div><div><span>Routing entropy</span><b>{ran ? result.routingEntropy.toFixed(3) : '—'}</b></div><div><span>激活专家比例</span><b>{ran ? pct(result.activeRatio, 0) : '—'}</b></div><div><span>通信代理成本</span><b>{ran ? result.communication.toFixed(0) : '—'}</b></div></div><div className='expert-loads'>{result.load.map((value, index) => <div key={`expert-${['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen'][index]}`}><span>E{index}</span><i><em className={result.raw[index] > result.maxPerExpert ? 'overflow' : ''} style={{ height: ran ? `${Math.max(4, value / result.maxPerExpert * 100)}%` : '4%' }} /></i><b>{ran ? `${value}/${result.raw[index]}` : '?'}</b><small>p={ran ? result.probs[index].toFixed(2) : '?'}</small></div>)}</div><div className={`diagnostic-callout ${result.overflow ? 'danger' : ''}`}>{result.overflow ? `容量不足或路由坍缩：${result.overflow} 个分配溢出。提高 CF/均衡权重，并确认任务质量未被过度均匀化。` : '负载在容量内；继续同时观察专家专门化、跨卡通信和能力切片。'}</div></div>
}
