import { useState } from 'react'
import { Play, RotateCcw } from 'lucide-react'
import { clamp, pct, softmax, entropy, kl } from '../foundation/math'

export function TemperatureLab() {
  const [temperature, setTemperature] = useState(3); const [alpha, setAlpha] = useState(.5); const [bias, setBias] = useState(.3); const [ran, setRan] = useState(false)
  const teacher = softmax([3.2, 2.8, -.5, -1.2], temperature); const student = softmax([3.2-bias, 2.8+bias, -.4, -1], temperature); const kd = kl(teacher, student) * temperature ** 2; const ce = -Math.log(Math.max(1e-9, student[0])); const total = alpha * ce + (1-alpha)*kd
  return <LabFrame onRun={() => setRan(true)} onReset={() => { setTemperature(3); setAlpha(.5); setBias(.3); setRan(false) }} controls={<><Range label='温度 T' value={temperature} min={.1} max={10} step={.1} set={setTemperature} /><Range label='α（CE 权重）' value={alpha} min={0} max={1} step={.02} set={setAlpha} /><Range label='学生偏差' value={bias} min={0} max={1} step={.02} set={setBias} /></>}><Metrics items={[['教师熵', entropy(teacher)], ['学生熵', entropy(student)], ['T²·KL', kd], ['混合 Loss', total]]} ran={ran} /><Bars values={teacher} compare={student} ran={ran} /><Insight>高 T 暴露更多暗知识，但过高会让分布近似均匀。必须同时看教师熵、学生熵、KL(T²) 与任务正确率。</Insight></LabFrame>
}

export function LossMixLab() {
  const [alpha,setAlpha]=useState(.5); const [temperature,setTemperature]=useState(3); const [hidden,setHidden]=useState(.15); const [attention,setAttention]=useState(.05); const [ran,setRan]=useState(false); const stability=clamp(1-Math.abs(alpha-.45)-Math.max(0,temperature-7)*.08-hidden*.1-attention*.2,0,1); const success=clamp(.62+(1-alpha)*.16+hidden*.08+attention*.04,0, .94); const cost=1+hidden*.5+attention*.8
  return <LabFrame onRun={()=>setRan(true)} onReset={()=>{setAlpha(.5);setTemperature(3);setHidden(.15);setAttention(.05);setRan(false)}} controls={<><Range label='α · CE' value={alpha} min={0} max={1} step={.02} set={setAlpha}/><Range label='温度 T' value={temperature} min={.5} max={10} step={.1} set={setTemperature}/><Range label='Hidden 权重' value={hidden} min={0} max={1} step={.02} set={setHidden}/><Range label='Attention 权重' value={attention} min={0} max={1} step={.02} set={setAttention}/></>}><Metrics items={[['任务成功率',success],['训练稳定性',stability],['一致率',clamp(.58+(1-alpha)*.35,0,1)],['训练成本倍数',cost]]} ran={ran} percentFirst={3}/><Insight>Hidden/Attention 项要做独立消融；跨结构需要 projector，并把教师中间态显存计入总成本。</Insight></LabFrame>
}

export function DataRecipeLab(){const [teacher,setTeacher]=useState(55);const [rollout,setRollout]=useState(20);const [human,setHuman]=useState(10);const [oss,setOss]=useState(15);const [ran,setRan]=useState(false);const sum=Math.max(1,teacher+rollout+human+oss);const retention=clamp(.7+rollout/sum*.16+human/sum*.25+oss/sum*.12,0, .98);const forget=clamp(.5-oss/sum*.9-rollout/sum*.35,0,.9);const cost=teacher*4+rollout*7+human*30+oss;return <LabFrame onRun={()=>setRan(true)} onReset={()=>{setTeacher(55);setRollout(20);setHuman(10);setOss(15);setRan(false)}} controls={<><Range label='教师生成 %' value={teacher} min={0} max={100} set={setTeacher}/><Range label='学生 rollout %' value={rollout} min={0} max={100} set={setRollout}/><Range label='真人标注 %' value={human} min={0} max={100} set={setHuman}/><Range label='开源 / Replay %' value={oss} min={0} max={100} set={setOss}/></>}><Metrics items={[['能力保留',retention],['遗忘风险',forget],['分布外泛化',clamp(.35+rollout/sum*.3+oss/sum*.25,0,1)],['成本指数',cost]]} ran={ran} percentFirst={3}/><div className='recipe-bar'>{[['教师',teacher],['Rollout',rollout],['真人',human],['开源',oss]].map(([name,value])=><i key={name} style={{width:`${Number(value)/sum*100}%`}} title={`${name}: ${(Number(value)/sum*100).toFixed(1)}%`}/>)}</div><Insight>比例自动归一化。教师多更像教师；rollout 缓解暴露偏差；开源/Replay 过低时灾难性遗忘上升。</Insight></LabFrame>}

export function SeqVsTokenLab(){const [length,setLength]=useState(512);const [teacher,setTeacher]=useState(.85);const [open,setOpen]=useState(true);const [ran,setRan]=useState(false);const rows=[['Token-KD',.66+teacher*.12-(open?length/50000:0),1],['Seq-KD',.62+teacher*.13-(open?.02:0),.65],['On-policy',.68+teacher*.14,2.3]] as const;return <LabFrame onRun={()=>setRan(true)} onReset={()=>{setLength(512);setTeacher(.85);setOpen(true);setRan(false)}} controls={<><Range label='序列长度' value={length} min={64} max={2048} step={32} set={setLength}/><Range label='教师质量' value={teacher} min={.5} max={.99} step={.01} set={setTeacher}/><label className='dist-toggle'><input type='checkbox' checked={open} onChange={e=>setOpen(e.target.checked)}/>开放生成任务</label></>}><table className='dist-table'><thead><tr><th>范式</th><th>成功率</th><th>暴露偏差</th><th>相对成本</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row[0]}><td>{row[0]}</td><td>{ran?pct(clamp(row[1],0,1)):'—'}</td><td>{ran?pct(index===2?.15:index===0?.55:.68):'—'}</td><td>{ran?`×${row[2]}`:'—'}</td></tr>)}</tbody></table><Insight>结构化任务优先 Token-KD；开放生成考虑混入 On-policy。采样温度、top-p 和束宽必须版本化。</Insight></LabFrame>}

function Range({label,value,min,max,step=1,set}:{label:string;value:number;min:number;max:number;step?:number;set:(value:number)=>void}){return <label className='dist-range'><span>{label}<b>{value.toFixed(step<1?2:0)}</b></span><input type='range' min={min} max={max} step={step} value={value} onChange={event=>set(clamp(Number(event.target.value),min,max))}/></label>}
function LabFrame({controls,children,onRun,onReset}:{controls:React.ReactNode;children:React.ReactNode;onRun:()=>void;onReset:()=>void}){return <div className='dist-lab-frame'><aside><h3>控制面板</h3>{controls}<div className='dist-run-actions'><button onClick={onRun}><Play/>运行</button><button onClick={onReset}><RotateCcw/>重置</button></div></aside><main>{children}</main></div>}
function Metrics({items,ran,percentFirst=0}:{items:[string,number][];ran:boolean;percentFirst?:number}){return <div className='dist-metrics'>{items.map(([label,value],index)=><div key={label}><span>{label}</span><b>{ran?(index<percentFirst?pct(value):value.toFixed(3)):'—'}</b></div>)}</div>}
function Bars({values,compare,ran}:{values:number[];compare:number[];ran:boolean}){return <div className='dist-bars'>{values.map((value,index)=><div key={`class-${['zero','one','two','three','four','five','six','seven','eight','nine'][index]}`}><span>c{index}</span><i><em style={{width:ran?`${value*100}%`:'0%'}}/><strong style={{width:ran?`${compare[index]*100}%`:'0%'}}/></i><b>{ran?pct(value):'?'}</b></div>)}</div>}
function Insight({children}:{children:React.ReactNode}){return <div className='dist-insight'>{children}</div>}
