import { useState } from 'react'
import { Play, RotateCcw } from 'lucide-react'
import { clamp, pct } from '../foundation/math'

export function TeacherBudgetLab(){const [student,setStudent]=useState(3);const [teacher,setTeacher]=useState(70);const [tokens,setTokens]=useState(2);const [gpu,setGpu]=useState(4000);const [ran,setRan]=useState(false);const needed=Math.max(50,tokens*student*150);const success=clamp(.52+.04*Math.log2(student+1)+.06*Math.log2(teacher/student+1)+.03*Math.log2(tokens+1),0,.94);return <Frame run={()=>setRan(true)} reset={()=>{setStudent(3);setTeacher(70);setTokens(2);setGpu(4000);setRan(false)}} controls={<><Range label='学生尺寸 B' value={student} min={.5} max={30} step={.5} set={setStudent}/><Range label='教师尺寸 B' value={teacher} min={3} max={400} set={setTeacher}/><Range label='训练 tokens B' value={tokens} min={.1} max={20} step={.1} set={setTokens}/><Range label='可用 GPU-hours' value={gpu} min={200} max={80000} step={200} set={setGpu}/></>}><Cards values={ran?[['任务成功率',pct(success)],['能力保留',pct(success/.9)],['所需 GPU-hours',needed.toFixed(0)],['预算结论',gpu>=needed?'PASS':'SHORT']]:[['任务成功率','—'],['能力保留','—'],['所需 GPU-hours','—'],['预算结论','—']]}/><Insight>教师—学生能力 gap 过小，蒸馏收益有限；GPU 估算必须额外纳入教师前向、rollout 与失败重跑。</Insight></Frame>}

export function BlackboxApiLab(){const [priceIn,setPriceIn]=useState(2);const [priceOut,setPriceOut]=useState(8);const [samples,setSamples]=useState(80000);const [out,setOut]=useState(900);const [cache,setCache]=useState(.9);const [cot,setCot]=useState(true);const [ran,setRan]=useState(false);const effectiveOut=out*(cot?1:.35);const gross=samples*(400*priceIn+effectiveOut*priceOut)/1e6;const total=gross*(1-cache*.7);return <Frame run={()=>setRan(true)} reset={()=>{setPriceIn(2);setPriceOut(8);setSamples(80000);setOut(900);setCache(.9);setCot(true);setRan(false)}} controls={<><Range label='输入 $/M tokens' value={priceIn} min={.1} max={20} step={.1} set={setPriceIn}/><Range label='输出 $/M tokens' value={priceOut} min={.1} max={60} step={.1} set={setPriceOut}/><Range label='样本量' value={samples} min={5000} max={500000} step={5000} set={setSamples}/><Range label='输出 tokens/query' value={out} min={50} max={3000} step={50} set={setOut}/><Range label='缓存复用率' value={cache} min={0} max={.95} step={.01} set={setCache}/><label className='dist-toggle'><input type='checkbox' checked={cot} onChange={e=>setCot(e.target.checked)}/>生成结构化 rationale</label></>}><Cards values={ran?[['毛费用',`$${gross.toFixed(0)}`],['缓存后费用',`$${total.toFixed(0)}`],['有效输出 tokens',effectiveOut.toFixed(0)],['能力迁移估算',pct(clamp(.77+(cot?.07:0),0,1))]]:[['毛费用','—'],['缓存后费用','—'],['有效输出 tokens','—'],['能力迁移估算','—']]}/><div className='risk-list'><b>高风险 · ToS / 许可版本与法务签字</b><b>高风险 · 教师停服与版本漂移</b><span>中风险 · PII、数据出境、CoT 数据许可</span></div><Insight>缓存 key 必须包含 Prompt hash 与教师版本；至少准备备份 API 和自有模型 fallback。</Insight></Frame>}

export function StackLab(){const [quant,setQuant]=useState<'FP16'|'INT8'|'INT4'>('INT8');const [spec,setSpec]=useState(true);const [student,setStudent]=useState(7);const [batch,setBatch]=useState(8);const [ran,setRan]=useState(false);const factor=quant==='FP16'?1:quant==='INT8'?.72:.55;const quality=quant==='FP16'?.99:quant==='INT8'?.965:.925;const tpot=40*(student/7)*factor*(spec?.65:1);const memory=student*(quant==='FP16'?2:quant==='INT8'?1:.5)+(spec?.3:0);return <Frame run={()=>setRan(true)} reset={()=>{setQuant('INT8');setSpec(true);setStudent(7);setBatch(8);setRan(false)}} controls={<><label className='dist-select'>量化<select value={quant} onChange={e=>setQuant(e.target.value as typeof quant)}><option>FP16</option><option>INT8</option><option>INT4</option></select></label><Range label='学生尺寸 B' value={student} min={1} max={30} set={setStudent}/><Range label='Batch' value={batch} min={1} max={64} set={setBatch}/><label className='dist-toggle'><input type='checkbox' checked={spec} onChange={e=>setSpec(e.target.checked)}/>Speculative decoding</label></>}><Cards values={ran?[['质量保留',pct(quality)],['TPOT',`${tpot.toFixed(1)} ms`],['显存',`${memory.toFixed(1)} GB`],['吞吐代理',`${(1000/tpot*batch).toFixed(0)} tok/s`]]:[['质量保留','—'],['TPOT','—'],['显存','—'],['吞吐代理','—']]}/><div className='stack-flow'><span>BF16 蒸馏</span><b>→</b><span>{quant} 量化</span><b>→</b><span>{spec?'Draft + Verify':'常规解码'}</span></div><Insight>顺序必须是蒸馏→量化→推测解码；INT4 需要覆盖长尾的校准集，acceptance rate 低于 0.6 时速推收益有限。</Insight></Frame>}

export function LaunchGate(){const [retention,setRetention]=useState(.92);const [hallucination,setHallucination]=useState(.04);const [safety,setSafety]=useState(.01);const [p95,setP95]=useState(520);const [cost,setCost]=useState(1.6);const [ran,setRan]=useState(false);const checks=[['能力保留',retention>=.9,pct(retention),'≥90%'],['幻觉率',hallucination<=.05,pct(hallucination),'≤5%'],['安全回归',safety<=.02,pct(safety),'≤2%'],['p95',p95<=600,`${p95}ms`,'≤600ms'],['单位成本',cost<=2,`$${cost.toFixed(2)}`,'≤$2'] ] as const;const fails=checks.filter(item=>!item[1]);const verdict=fails.some(item=>item[0]==='安全回归'||item[0]==='能力保留')?'No-Go':fails.length?'Hold':'Go';return <Frame run={()=>setRan(true)} reset={()=>{setRetention(.92);setHallucination(.04);setSafety(.01);setP95(520);setCost(1.6);setRan(false)}} controls={<><Range label='能力保留' value={retention} min={.5} max={.99} step={.01} set={setRetention}/><Range label='幻觉率' value={hallucination} min={0} max={.2} step={.005} set={setHallucination}/><Range label='安全回归' value={safety} min={0} max={.08} step={.002} set={setSafety}/><Range label='p95 ms' value={p95} min={80} max={2000} step={10} set={setP95}/><Range label='单位成本 $/1k' value={cost} min={.1} max={10} step={.1} set={setCost}/></>}><div className={`launch-verdict ${verdict.toLowerCase()}`}><span>上线结论</span><b>{ran?verdict:'待运行'}</b><p>{ran?(verdict==='Go'?'Shadow 5–7 天 → Canary 1%→5%→15% → A/B。':`优先修复：${fails.map(item=>item[0]).join('、')}`):'运行后按五道闸门确定 Go / Hold / No-Go。'}</p></div><table className='dist-table'><thead><tr><th>闸门</th><th>实测</th><th>门槛</th><th>结论</th></tr></thead><tbody>{checks.map(item=><tr key={item[0]}><td>{item[0]}</td><td>{ran?item[2]:'—'}</td><td>{item[3]}</td><td className={item[1]?'pass-text':'bad-text'}>{ran?(item[1]?'PASS':'FAIL'):'—'}</td></tr>)}</tbody></table><Insight>安全或核心能力越界直接 No-Go；其它单项越界 Hold。Kill-switch 必须演练且有明确负责人。</Insight></Frame>}

function Range({label,value,min,max,step=1,set}:{label:string;value:number;min:number;max:number;step?:number;set:(value:number)=>void}){return <label className='dist-range'><span>{label}<b>{value.toFixed(step<1?2:0)}</b></span><input type='range' min={min} max={max} step={step} value={value} onChange={e=>set(clamp(Number(e.target.value),min,max))}/></label>}
function Frame({controls,children,run,reset}:{controls:React.ReactNode;children:React.ReactNode;run:()=>void;reset:()=>void}){return <div className='dist-lab-frame'><aside><h3>控制面板</h3>{controls}<div className='dist-run-actions'><button onClick={run}><Play/>运行</button><button onClick={reset}><RotateCcw/>重置</button></div></aside><main>{children}</main></div>}
function Cards({values}:{values:[string,string][]}){return <div className='dist-metrics'>{values.map(value=><div key={value[0]}><span>{value[0]}</span><b>{value[1]}</b></div>)}</div>}
function Insight({children}:{children:React.ReactNode}){return <div className='dist-insight'>{children}</div>}
