import { useEffect, useState } from 'react'
import { ArrowRight, BookOpen, FlaskConical, Link2 } from 'lucide-react'
import { distillModules } from '../../distillData'
import DecisionBriefPractice from '../course/DecisionBriefPractice'

type Go = (page: string, options?: Record<string, string>) => void

export default function DistillCourse({ initialModule, go }: { initialModule?: string; go: Go }) {
  const [activeId, setActiveId] = useState(initialModule && distillModules.some((module) => module.id === initialModule) ? initialModule : distillModules[0].id)
  useEffect(() => { if (initialModule && distillModules.some((module) => module.id === initialModule)) setActiveId(initialModule) }, [initialModule])
  const active = distillModules.find((module) => module.id === activeId) ?? distillModules[0]
  const index = distillModules.indexOf(active)
  const select = (id: string) => { setActiveId(id); go('distill-course', { module: id }) }
  return <section className='distill-scope'><header className='distill-page-head'><span>DISTILLATION COURSE · 12 MODULES</span><h1>{active.code} · {active.title}</h1><p>{active.lead}</p><div>机制级教学仿真 · 不代表任何商业模型或线上参数</div><button type='button' className='strategy-route-entry' onClick={() => go('strategy-case', { case: 'distill-retention' })}>该路线策略案例<ArrowRight /></button></header><div className='distill-layout'><aside className='distill-toc'><h2>蒸馏课程目录</h2>{distillModules.map((module) => <button key={module.id} className={module.id === active.id ? 'active' : ''} onClick={() => select(module.id)}><span>{module.code}</span><b>{module.title}</b></button>)}</aside><main className='distill-course-body'><article className='distill-lead-card'><span>{active.code}</span><h2>{active.title}</h2><p>{active.lead}</p><div className='distill-actions'>{active.labs.map((lab) => <button key={lab} onClick={() => go('distill-lab', { experiment: lab })}><FlaskConical />打开 {lab}<ArrowRight /></button>)}<button className='secondary' onClick={() => go('handbook')}><BookOpen />统一手册</button>{active.foundation ? <button className='secondary' onClick={() => go('foundation', { node: active.foundation ?? 'probability' })}><Link2 />返回算法先修</button> : null}</div></article>{active.formula ? <article className='distill-section formula'><h3>核心公式</h3><pre>{active.formula}</pre></article> : null}<div className='distill-section-grid'><article className='distill-section'><h3>机制</h3><ul>{active.mechanism.map((item) => <li key={item}>{item}</li>)}</ul></article><article className='distill-section'><h3>工程约束</h3><ul>{active.constraints.map((item) => <li key={item}>{item}</li>)}</ul></article><article className='distill-section tradeoff'><h3>Trade-off</h3><ul>{active.tradeoffs.map((item) => <li key={item}>{item}</li>)}</ul></article><article className='distill-section checklist'><h3>评审 Checklist</h3><ul>{active.checklist.map((item) => <li key={item}>{item}</li>)}</ul></article></div><article className='distill-section case'><h3>案例推演</h3><p>{active.caseStudy}</p></article>{active.practice ? <DecisionBriefPractice key={active.practice.id} practice={active.practice} /> : null}<footer className='distill-pagination'><button disabled={index === 0} onClick={() => select(distillModules[index - 1].id)}>← 上一模块</button><span>{index + 1} / {distillModules.length}</span><button disabled={index === distillModules.length - 1} onClick={() => select(distillModules[index + 1].id)}>下一模块 →</button></footer></main></div></section>
}
