import type { CSSProperties } from 'react';

const customProperties = {
  '--lab-blue': '#78a7ff',
  '--lab-mint': '#72dfb2',
  '--lab-line': '#ffffff24',
} as CSSProperties;

export const workshopStyles = {
  root: { ...customProperties, maxWidth: 980, margin: 'auto' },
  intro: {
    display: 'grid',
    gridTemplateColumns: 'var(--k3-intro-columns,auto 1fr auto)',
    gap: 16,
    alignItems: 'center',
    padding: 22,
    border: '1px solid var(--lab-line)',
    borderRadius: 16,
    background: 'linear-gradient(135deg,#ffffff0d,#78a7ff12)',
    marginBottom: 24,
  },
  introIcon: { color: 'var(--lab-mint)' },
  introTitle: { margin: 0, fontSize: 20 },
  introText: { margin: '5px 0 0', color: '#c8d2df', lineHeight: 1.6 },
  introProgress: {
    gridColumn: 'var(--k3-progress-column,auto)',
    fontSize: 24,
    color: 'var(--lab-mint)',
  },
  notice: {
    padding: '12px 14px',
    borderLeft: '3px solid var(--lab-mint)',
    background: '#72dfb218',
    color: '#eefbf6',
  },
  step: {
    display: 'block',
    minHeight: 0,
    padding: 0,
    borderBottom: '1px solid var(--lab-line)',
    opacity: 1,
    background: 'transparent',
  },
  stepHeader: {
    display: 'grid',
    gridTemplateColumns: '42px 1fr auto',
    gap: 14,
    alignItems: 'center',
    padding: '20px 4px',
  },
  stepButton: {
    display: 'grid',
    placeItems: 'center',
    width: 36,
    height: 36,
    borderRadius: '50%',
    border: '1px solid #ffffff55',
    background: '#ffffff08',
    color: 'white',
    fontWeight: 800,
  },
  activeStepButton: { borderColor: 'var(--lab-blue)', background: '#78a7ff24' },
  stepLabel: {
    color: 'var(--lab-blue)',
    fontWeight: 800,
    letterSpacing: '.08em',
    textTransform: 'uppercase',
  },
  stepTitle: { margin: '2px 0 4px', fontSize: 21 },
  stepLead: { margin: 0, fontSize: 14, lineHeight: 1.5, color: '#c3cedb' },
  stepStatus: {
    display: 'var(--k3-badge-display,inline)',
    fontSize: 12,
    color: '#c3cedb',
    border: '1px solid var(--lab-line)',
    borderRadius: 999,
    padding: '6px 9px',
  },
  experiment: {
    margin: '0 0 28px var(--k3-experiment-margin,52px)',
    padding: 'var(--k3-experiment-padding,22px)',
    border: '1px solid var(--lab-line)',
    borderRadius: 14,
    background: '#151c24',
  },
  conclusion: {
    display: 'flex',
    gap: 11,
    alignItems: 'flex-start',
    marginTop: 18,
    padding: 15,
    borderRadius: 10,
    background: '#72dfb215',
    border: '1px solid #72dfb244',
  },
  conclusionIcon: { flex: '0 0 auto', color: 'var(--lab-mint)' },
  conclusionText: { margin: 0, lineHeight: 1.6 },
  conclusionLabel: { display: 'block', color: 'var(--lab-mint)' },
  details: {
    marginTop: 14,
    borderTop: '1px solid var(--lab-line)',
    paddingTop: 14,
    color: '#bac7d5',
  },
  summaryToggle: { cursor: 'pointer', color: '#dce5ef', fontWeight: 700 },
  explanation: { lineHeight: 1.65 },
  code: {
    overflow: 'auto',
    padding: 14,
    borderRadius: 9,
    background: '#090e13',
    color: '#b8d0ff',
    fontSize: 12,
    lineHeight: 1.6,
  },
  actions: { alignItems: 'center', marginTop: 18 },
  actionHint: { color: '#aebccd' },
  summary: {
    marginTop: 28,
    padding: 25,
    border: '1px solid #72dfb255',
    borderRadius: 14,
    background: 'linear-gradient(145deg,#72dfb211,#78a7ff12)',
  },
  summaryLabel: {
    color: 'var(--lab-mint)',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '.1em',
  },
  summaryTitle: { fontSize: 24 },
  summaryItem: { display: 'flex', alignItems: 'flex-start', gap: 7, lineHeight: 1.6 },
  summaryIcon: { flex: '0 0 auto', marginTop: 5, color: 'var(--lab-mint)' },
} satisfies Record<string, CSSProperties>;

export const experimentStyles = {
  field: {
    display: 'grid',
    gap: 7,
    maxWidth: 'var(--k3-field-width,560px)',
    color: '#dce5ef',
    fontSize: 13,
    fontWeight: 700,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid #ffffff38',
    borderRadius: 9,
    background: '#0f151c',
    color: 'white',
    padding: '12px 14px',
    fontSize: 17,
    outline: 'none',
  },
  run: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '16px 0',
    border: 0,
    borderRadius: 9,
    background: 'var(--lab-blue)',
    color: '#101820',
    padding: '11px 16px',
    fontWeight: 800,
  },
  compare: {
    display: 'grid',
    gridTemplateColumns: 'var(--k3-compare-columns,minmax(0,1fr) 24px minmax(0,1fr))',
    gap: 14,
    alignItems: 'stretch',
    marginTop: 16,
  },
  compareArrow: {
    alignSelf: 'center',
    color: '#8ea0b5',
    transform: 'var(--k3-arrow-transform,none)',
    justifySelf: 'var(--k3-arrow-justify,auto)',
  },
  compareCard: {
    minHeight: 'var(--k3-card-height,150px)',
    border: '1px solid #ffffff24',
    borderRadius: 12,
    padding: 16,
    background: '#0e141b',
    overflow: 'hidden',
  },
  afterCard: { borderColor: '#72dfb255', background: '#12211e' },
  compareLabel: {
    display: 'block',
    marginBottom: 14,
    color: '#9fadc0',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '.1em',
  },
  largeText: { fontSize: 19, lineHeight: 1.6, color: 'white' },
  tokenRow: { display: 'flex', gap: 7, flexWrap: 'wrap' },
  token: {
    position: 'relative',
    minWidth: 28,
    padding: '12px 9px 8px',
    textAlign: 'center',
    border: '1px solid #72dfb288',
    borderRadius: 8,
    background: '#72dfb21b',
    color: 'white',
    fontWeight: 800,
  },
  tokenIndex: { position: 'absolute', top: 1, left: 4, color: '#9ce9c8', fontSize: 8 },
  wait: { color: '#93a2b5', lineHeight: 1.6 },
  cursor: {
    display: 'inline-block',
    width: 2,
    height: '1.2em',
    marginLeft: 3,
    verticalAlign: 'middle',
    background: 'var(--lab-blue)',
    animation: 'var(--k3-cursor-animation,k3-blink 1s steps(1) infinite)',
  },
  bars: { display: 'grid', gap: 8, marginTop: 12 },
  barRow: {
    display: 'grid',
    gridTemplateColumns: '42px 1fr 36px',
    gap: 7,
    alignItems: 'center',
    fontSize: 12,
  },
  barToken: { fontWeight: 800 },
  barTrack: { height: 8, background: '#ffffff18', borderRadius: 99, overflow: 'hidden' },
  barFill: {
    display: 'block',
    height: '100%',
    background: 'linear-gradient(90deg,var(--lab-blue),var(--lab-mint))',
    borderRadius: 99,
    transition: 'var(--k3-bar-transition,width .4s ease)',
  },
  barScore: { textAlign: 'right', color: '#c9d5e4', fontSize: 11 },
  picked: { margin: '13px 0 0', color: 'var(--lab-mint)', fontWeight: 800 },
  problem: { display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' },
  problemValue: { padding: '8px 11px', borderRadius: 8, background: '#ffffff10', fontSize: 18 },
  muted: { color: '#aebccd', fontSize: 13 },
  context: {
    maxWidth: 560,
    padding: '13px 15px',
    border: '1px dashed #ffffff38',
    borderRadius: 10,
    background: '#ffffff08',
  },
  contextText: { margin: '6px 0 0' },
  result: { display: 'block', marginTop: 14, color: 'var(--lab-mint)' },
  choices: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  choice: {
    border: '1px solid #ffffff38',
    borderRadius: 8,
    background: 'transparent',
    color: '#dce5ef',
    padding: '9px 12px',
  },
  activeChoice: { borderColor: 'var(--lab-blue)', background: '#78a7ff22', color: 'white' },
  messages: { display: 'grid', gap: 8 },
  message: {
    display: 'grid',
    gridTemplateColumns: '42px 1fr',
    gap: 8,
    margin: 0,
    padding: 8,
    borderRadius: 8,
    background: '#ffffff0a',
    fontSize: 12,
    lineHeight: 1.5,
  },
  userRole: { color: 'var(--lab-blue)' },
  assistantRole: { color: 'var(--lab-mint)' },
  modelSize: { fontSize: 24 },
  modelMyth: { color: '#aebccd', lineHeight: 1.6 },
  routingTitle: { marginTop: 0, fontWeight: 800 },
  experts: { display: 'flex', gap: 5, flexWrap: 'wrap', marginBottom: 12 },
  expert: {
    padding: '4px 6px',
    border: '1px solid #72dfb266',
    borderRadius: 5,
    background: '#72dfb219',
    color: '#c9f5e2',
    fontSize: 10,
  },
  routingNote: { color: '#9ce9c8' },
} satisfies Record<string, CSSProperties>;

export const K3_INTERACTION_CSS = `
@keyframes k3-blink{50%{opacity:0}}
.k3-workshop .k3-field input:focus{border-color:var(--lab-blue);box-shadow:0 0 0 3px #78a7ff20}
.k3-workshop .k3-run:hover:not(:disabled),.k3-workshop .k3-step-button:hover:not(:disabled){filter:brightness(1.08);transform:translateY(-1px)}
.k3-workshop .k3-run:disabled,.k3-workshop .k3-actions button:disabled{opacity:.5;cursor:not-allowed}
.k3-workshop button:focus-visible,.k3-workshop summary:focus-visible{outline:2px solid var(--lab-blue);outline-offset:3px}
@media(max-width:760px){.k3-workshop{--k3-intro-columns:auto 1fr;--k3-progress-column:2;--k3-badge-display:none;--k3-experiment-margin:0px;--k3-experiment-padding:16px;--k3-compare-columns:1fr;--k3-arrow-transform:rotate(90deg);--k3-arrow-justify:center;--k3-card-height:120px;--k3-field-width:none}}
@media(prefers-reduced-motion:reduce){.k3-workshop{--k3-cursor-animation:none;--k3-bar-transition:none}}
`;
