import type { CourseEntry } from '../types'

export const courseEntries = [
  { id: 'course:math-primer', type: 'course', title: '数学零层', summary: '先把公式里的符号和基础概念翻译成人话。', route: { page: 'math-primer' }, tags: ['foundation', 'math'], level: 'beginner', status: 'published', order: 0, audience: '第一次接触 AI 公式的学习者', outcome: '理解求和、概率、向量、梯度、损失与熵。', routeKind: 'main' },
  { id: 'course:foundation', type: 'course', title: '算法基础', summary: '从概率分布走到 Transformer、MoE 与蒸馏。', route: { page: 'foundation' }, tags: ['foundation'], level: 'beginner', status: 'published', order: 1, audience: '需要补齐最小数学与机制直觉的人', outcome: '看懂模型训练与架构的核心机制。', labRoute: { page: 'foundation-lab', options: { experiment: 'softmax-ce' } }, relatedLabIds: ['lab:foundation:softmax-ce'], relatedCaseIds: ['case:foundation-feedback-loop'], routeKind: 'main' },
  { id: 'course:decision-math', type: 'course', title: 'AI 决策数学', summary: '用短案例把概率、优化、因果和序贯决策变成判断。', route: { page: 'decision-math' }, tags: ['math', 'reliability'], level: 'beginner', status: 'published', order: 2, audience: '需要用数字支持策略判断的产品与运营', outcome: '用数据说明证据是否足以支持行动。', relatedCaseIds: ['case:calibration-threshold'], routeKind: 'main' },
  { id: 'course:llm', type: 'course', title: '大语言模型系统', summary: '连接训练、推理、服务和评估决策。', route: { page: 'expert-llm' }, tags: ['llm', 'reliability'], level: 'intermediate', status: 'published', order: 3, audience: 'LLM 产品、研发与系统架构师', outcome: '评估上下文、服务成本与检索质量。', labRoute: { page: 'expert-lab', options: { experiment: 'kv-cost' } }, relatedLabIds: ['lab:expert:kv-cost'], relatedCaseIds: ['case:context-window-budget'], routeKind: 'main' },
  { id: 'course:k3-build-lab', type: 'course', title: 'K3 Build Lab', summary: '从 Kimi K3 参数表出发，跑通自己的第一台模型。', route: { page: 'k3-build-lab' }, tags: ['llm', 'foundation'], level: 'beginner', status: 'published', order: 4, audience: '想动手理解和运行大模型的学习者', outcome: '看懂 MoE 架构，估算显存并完成最小模型闭环。', labRoute: { page: 'k3-build-lab', options: { section: 'lab' } }, relatedLabIds: ['lab:expert:k3-build-lab'], routeKind: 'branch' },
  { id: 'course:image', type: 'course', title: '图像生成', summary: '理解扩散、控制与生产评估。', route: { page: 'expert-image' }, tags: ['image', 'multimodal'], level: 'intermediate', status: 'published', order: 4, audience: '图像产品、内容与创作工具团队', outcome: '平衡生成质量、控制能力与单位成本。', labRoute: { page: 'expert-lab', options: { experiment: 'diffusion-flow' } }, relatedLabIds: ['lab:expert:diffusion-flow'], relatedCaseIds: ['case:image-unit-cost'], routeKind: 'branch' },
  { id: 'course:agent', type: 'course', title: '智能体系统', summary: '掌握循环执行、工具、记忆、安全与上线。', route: { page: 'expert-agent' }, tags: ['agent', 'reliability'], level: 'intermediate', status: 'published', order: 5, audience: '正在把模型接入工具和业务流程的人', outcome: '设计可终止、可验证、可回滚的任务闭环。', labRoute: { page: 'agent-lab', options: { experiment: 'loop-simulator' } }, relatedLabIds: ['lab:agent:loop-simulator'], relatedCaseIds: ['case:refund-gate'], routeKind: 'main' },
  { id: 'course:agent-book', type: 'course', title: '智能体工程手册', summary: '深入上下文、Harness、评估口径与持续进化。', route: { page: 'agent-book' }, tags: ['agent', 'agent-book', 'reliability'], level: 'advanced', status: 'published', order: 6, audience: '需要系统化 Agent 工程方法的实践者', outcome: '把工程判断变成可验证、可回滚的方案。', labRoute: { page: 'agent-book-lab', options: { experiment: 'pass-at-k' } }, relatedLabIds: ['lab:agent-book:pass-at-k'], relatedCaseIds: ['case:new-information'], routeKind: 'main' },
  { id: 'course:distill', type: 'course', title: '模型蒸馏', summary: '设计教师、数据、损失与上线闸门。', route: { page: 'distill-course' }, tags: ['distillation', 'reliability'], level: 'advanced', status: 'published', order: 7, audience: '关注能力保持、成本与部署的人', outcome: '在质量、速度、成本与风险之间设定闸门。', labRoute: { page: 'distill-lab', options: { experiment: 'launch-gate' } }, relatedLabIds: ['lab:distill:launch-gate'], relatedCaseIds: ['case:distill-retention'], routeKind: 'main' },
  { id: 'course:self-evolving', type: 'course', title: '自进化', summary: '判断自动评估何时可信，何时必须停手。', route: { page: 'strategy-case', options: { case: 'evaluator-trust' } }, tags: ['frontier', 'agent', 'reliability'], level: 'advanced', status: 'published', order: 8, audience: '策略产品与 Agent 工程负责人', outcome: '识别 evaluator 与 policy 同步漂移。', relatedCaseIds: ['case:evaluator-trust'], routeKind: 'frontier' },
  { id: 'course:world-model', type: 'course', title: '世界模型', summary: '比较真实实验、LLM 推演和轻量模拟器。', route: { page: 'strategy-case', options: { case: 'simulator-vs-reality' } }, tags: ['frontier', 'reliability'], level: 'advanced', status: 'published', order: 9, audience: '关心仿真、规划与新方向的团队', outcome: '识别模拟误差并设置真实验证护栏。', relatedCaseIds: ['case:simulator-vs-reality'], routeKind: 'frontier' },
] as const satisfies readonly CourseEntry[]
