import type { DecisionBriefPracticeData } from './components/course/DecisionBriefPractice'

export type ExpertTrack = 'llm' | 'image'

export type ExpertModule = {
  id: string
  no: string
  title: string
  subtitle: string
  formula: string
  formulaNote: string
  architecture: string
  constraints: string[]
  decision: string
  metrics: string[]
  tradeoff: string
  failures: string[]
  review: string[]
  caseStudy: string
  practice?: DecisionBriefPracticeData
}

const sharedRubric = [
  '决策明确写出 Go（上线）、Hold（暂缓）或 No-Go（不上线），并说明适用流量。',
  '指标同时包含结果指标与延迟、成本或风险护栏。',
  '闸门有数字阈值、观察窗口和触发后的回滚动作。',
  '下一步可由明确负责人在一个迭代内执行并产出证据。',
]

const expertLLMPractices: Record<string, DecisionBriefPracticeData> = {
  kv: {
    id: 'llm-kv-capacity',
    businessInput: '报告助手需支持 40 路并发、32K 输入；模型 32 层、8 个 KV（Key-Value，键值）头、头维 128，缓存使用 FP16（16 位浮点）共 2 字节。',
    facts: ['显存预算：24 GiB（吉比字节）', '输出上限：1K token', '需预留 20% 运行时与碎片空间'],
    calculation: { label: '峰值 KV 缓存', question: '按输入阶段的 40 路峰值，计算 KV 缓存占用。', formula: '2 × 32 × 32,000 × 8 × 128 × 2 × 40 ÷ 1,073,741,824', values: [2, 32, 32000, 8, 128, 2, 40, 1 / 1073741824], method: 'multiply', unit: ' GiB', precision: 2, tolerance: 0.02 },
    template: { decision: 'Hold：24 GiB 单卡不能直接接纳 40 路 32K 请求，先限制并发并验证 KV 量化。', metrics: 'KV 池利用率、OOM（显存溢出）率、TTFT（首 token 延迟）p95、TPOT（每 token 延迟）p95。', gate: 'KV 占用≤可用显存 80%，OOM=0，TTFT/TPOT 均达标才 Go；否则自动降并发。', nextStep: '容量负责人用真实长度分布压测 GQA（分组查询注意力）与 8-bit KV，两天内给出并发曲线。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '只计算模型权重，漏掉并发 KV。', fix: '按层数、长度、KV 头、头维、字节数与并发逐项列式。' }, { mistake: '按平均长度承诺容量。', fix: '用长度×并发联合分布压测，并预留碎片空间。' }],
  },
  serving: {
    id: 'llm-serving-goodput',
    businessInput: '聊天服务压测每分钟生成 240,000 token，其中 180,000 token 来自在 SLO（服务等级目标）内完成的请求。',
    facts: ['TTFT（首 token 延迟）p95（第 95 百分位）目标：≤1.2 秒', 'TPOT（每 token 延迟）p95 目标：≤80 毫秒', 'GPU（图形处理器）利用率：92%'],
    calculation: { label: 'Goodput（有效吞吐）占比', question: '计算满足 SLO 的有效 token 占总生成 token 的比例。', formula: '180,000 ÷ 240,000 × 100', values: [180000 / 240000, 100], method: 'multiply', unit: '%', precision: 1, tolerance: 0.1 },
    template: { decision: 'Hold：GPU 利用率高但有效吞吐仅 75%，先优化调度而非继续扩 batch。', metrics: 'Goodput、TTFT p95、TPOT p95、prefill/decode 队列长度。', gate: 'Goodput≥90%，且 TTFT≤1.2 秒、TPOT≤80 毫秒持续 30 分钟才 Go。', nextStep: 'Serving 负责人对比 chunked prefill（分块预填充）与 prefill/decode 解耦配置。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '把裸 TPS（每秒 token 数）当作用户价值。', fix: '分子只计入满足 SLO 的 token。' }, { mistake: '只报平均延迟。', fix: '同时监控 TTFT 与 TPOT 的 p95 及队列。' }],
  },
  evaluation: {
    id: 'llm-evaluation-ci',
    businessInput: '新模型在 1,000 个独立任务中成功 720 次，产品希望用 95% CI（置信区间）判断结果是否稳定超过 70%。',
    facts: ['样本比例 p̂=0.72', '正态近似系数：1.96', '上线下界要求：≥70%'],
    calculation: { label: '95% CI 半宽', question: '用大样本近似计算置信区间半宽。', formula: '1.96 × √(0.72 × 0.28 ÷ 1,000) × 100', values: [1.96, Math.sqrt(0.72 * 0.28 / 1000), 100], method: 'multiply', unit: ' pp（百分点）', precision: 2, tolerance: 0.02 },
    template: { decision: 'Hold：点估计 72%，但 95% CI 下界约 69.2%，尚不能证明超过 70%。', metrics: '任务成功率、95% CI、高风险切片最差值、人评一致性。', gate: '总体 CI 下界≥70%，且任一高风险切片不低于基线 2pp（百分点）才 Go。', nextStep: '评测负责人补充独立样本并对代码与长上下文切片分层抽样。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '只比较 72% 与 70% 两个点估计。', fix: '用区间下界做上线判断，并披露样本量。' }, { mistake: '总分掩盖关键切片回退。', fix: '为高风险切片单独设最低闸门。' }],
  },
  safety: {
    id: 'llm-safety-residual-risk',
    businessInput: '导出工具的固有风险评分为 80/100；权限校验、参数约束与人工确认合计控制覆盖率估算为 75%。',
    facts: ['外部网页内容按不可信数据处理', '跨租户导出默认拒绝', '高影响动作需人工确认'],
    calculation: { label: '残余风险', question: '按教学近似计算控制后的残余风险分。', formula: '80 × (1 − 75%)', values: [80, 0.25], method: 'multiply', unit: ' 分', precision: 1, tolerance: 0.1 },
    template: { decision: 'No-Go：残余风险 20 分高于导出工具 10 分红线，继续缩小权限与暴露面。', metrics: '注入 ASR（攻击成功率）、越权尝试、误拒率、DLP（数据防泄漏）命中。', gate: '残余风险≤10、注入 ASR≤1%、跨租户成功数=0 才允许内部灰度。', nextStep: '安全负责人增加租户资源绑定与脱敏沙箱红队测试，复核控制覆盖率。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '让模型自己判断是否有权限。', fix: '在模型外的策略执行点校验主体、资源与动作。' }, { mistake: '只测漏拦，不看误拒。', fix: '攻击集与正常业务集同时报告 ASR 和误拒率。' }],
  },
}

const expertImagePractices: Record<string, DecisionBriefPracticeData> = {
  'image-eval': {
    id: 'image-effective-cost',
    businessInput: '海报模型一轮生成与重试成本 100 元、审核 20 元、后处理 30 元，最终有 60 张通过业务验收。',
    facts: ['初始生成：100 张', 'OCR（光学字符识别）硬约束', '设计师采用率目标：≥65%'],
    calculation: { label: '单位有效图成本', question: '计算每张通过验收图片的全链路成本。', formula: '(100 + 20 + 30) ÷ 60', values: [150, 60], method: 'divide', unit: ' 元/张', precision: 2, tolerance: 0.02 },
    template: { decision: 'Hold：先以 2.50 元/有效图为成本基线，不因 CLIPScore（图文匹配分）单项提升直接上线。', metrics: '有效图率、OCR 精确匹配、设计师采用率、单位有效图成本、安全泄漏率。', gate: '采用率≥65%、OCR≥98%、安全泄漏=0 且成本≤2.50 元/张才 Go。', nextStep: '图像评测负责人补齐文字、人像与多样性切片的盲评。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '成本分母使用生成总数。', fix: '分母只使用最终通过业务验收的图片数。' }, { mistake: '用 FID（弗雷歇起始距离）评价单图。', fix: '集合指标与业务人评、硬约束检测分开报告。' }],
  },
  pipeline: {
    id: 'image-pipeline-yield',
    businessInput: '图像链路四个关键阶段通过率分别为 98%、95%、92%、97%，先用独立近似估算端到端有效图率。',
    facts: ['阶段：规划、基础生成、精修、检查', '当前整链重试', '目标有效图率：≥85%'],
    calculation: { label: 'E2E（端到端）有效图率', question: '计算四阶段通过率乘积。', formula: '98% × 95% × 92% × 97% × 100', values: [0.98, 0.95, 0.92, 0.97, 100], method: 'multiply', unit: '%', precision: 1, tolerance: 0.1 },
    template: { decision: 'Hold：独立近似有效图率约 83.1%，先修复 92% 的精修阶段并改为定向重试。', metrics: '阶段通过率、E2E 有效图率、重试深度、队列 p95、身份回归率。', gate: 'E2E≥85%、身份回归≤1%、整链重试下降 30% 后再 Go。', nextStep: 'Pipeline（流水线）负责人保留 trace ID（追踪标识），对精修失败做 100 例回放。' },
    rubric: sharedRubric,
    pitfalls: [{ mistake: '看到每段都超过 90% 就判断整链健康。', fix: '计算乘积并定位最低通过率阶段。' }, { mistake: '失败后从头重试整条链路。', fix: '按失败分类定向重试并缓存已通过阶段。' }],
  },
}

export const expertLLMModules: ExpertModule[] = [
  {
    id: 'scaling', no: 'L01', title: 'Scaling Laws 与算力最优', subtitle: '先分预算，再谈参数规模',
    formula: 'L(N,D) ≈ L∞ + A·N⁻ᵅ + B·D⁻ᵝ；训练 FLOPs ≈ 6ND',
    formulaNote: 'N 为参数量、D 为训练 token。Chinchilla-style 直觉：固定算力下，参数与数据应共同增长；常见教学近似 D≈20N 不是跨架构定律。',
    architecture: '把预训练视作参数、数据、算力三方预算优化，而不是“模型越大越好”。先用小规模 runs 拟合损失曲线，再选择等算力前沿。',
    constraints: ['高质量数据可能先于算力耗尽', '数据去重与混合比例改变有效 D', '训练 FLOPs 不含数据治理、失败重跑与后训练'],
    decision: '预算固定时，若数据不足则不要盲目扩 N；若线上成本受限，优先把预算留给高质量数据、蒸馏和后训练。',
    metrics: ['validation loss / perplexity', '每 token 训练 FLOPs', '数据重复率与质量切片', '预测曲线残差'],
    tradeoff: '大 N 提升容量但增加训练/推理成本；大 D 改善利用率但受数据质量和授权边界约束。',
    failures: ['照搬 20 tokens/param 作为硬规则', '只看训练 loss 不看领域切片', '忽略 tokenizer 与数据去重导致有效 token 虚高'],
    review: ['等算力基线是什么？', '边际 loss 收益如何映射到产品指标？', '数据枯竭时缩模型还是扩合成数据？'],
    caseStudy: '预算只能增加 2×：比较“参数翻倍但数据不变”与“参数不变、增加清洗后的领域 token”，给出试验矩阵与停训阈值。',
  },
  {
    id: 'moe', no: 'L02', title: 'Dense vs MoE', subtitle: '总参数、激活参数与通信不是一回事',
    formula: 'y=Σᵢ gᵢ(x)Eᵢ(x), Top-k；aux loss ∝ load imbalance',
    formulaNote: 'MoE 每 token 只激活 k 个专家，可提升总容量而控制激活 FLOPs；但 all-to-all、路由与专家并行会带来系统成本。',
    architecture: 'Dense 每层激活全部参数；MoE 用 router 将 token 分发到少数专家，并设置 capacity factor、丢弃/溢出策略和负载均衡损失。',
    constraints: ['跨卡 all-to-all 延迟', '热门专家过载与 token dropping', '小 batch 下专家利用率差', '部署拓扑受显存与网络限制'],
    decision: '离线大吞吐、集群互联强且容量收益明确时考虑 MoE；低延迟、小流量或边缘部署优先 Dense。',
    metrics: ['expert load CV', 'router entropy', 'token drop rate', 'active params/token', 'all-to-all p95'],
    tradeoff: 'MoE 以通信和调度复杂度换参数容量；Dense 以更高激活计算换部署简单和稳定延迟。',
    failures: ['路由塌缩到少数专家', '宣称总参数却隐藏激活参数', '训练均衡但线上领域流量导致热点'],
    review: ['capacity factor 多大？', '专家跨机还是机内？', '路由日志能否按语言/任务切片？'],
    caseStudy: '客服流量在大促时集中到退款领域：推演专家热点、排队和降级到 Dense backup 的触发条件。',
  },
  {
    id: 'position', no: 'L03', title: 'RoPE、ALiBi 与长上下文', subtitle: '“支持 128K”不等于能用好 128K',
    formula: 'RoPE: q̃ₘ=R(mθ)q；PI: m→m/s；ALiBi: scoreᵢⱼ−a·|i−j|',
    formulaNote: 'RoPE 旋转注入相对位置信息；位置插值压缩位置索引以外推。外推会改变频率分布，必须用任务评估验证。',
    architecture: '位置方法、训练长度、继续预训练和推理缩放共同决定长上下文能力；系统还需检索、分段和证据布局。',
    constraints: ['注意力计算随长度二次增长', '训练长度外相位分布漂移', 'lost-in-the-middle', '长输入增加 TTFT 与缓存占用'],
    decision: '先判断任务是否真需全量长上下文；可检索任务优先 RAG，跨段推理再投入长上下文适配。',
    metrics: ['needle retrieval by depth', 'multi-needle accuracy', '长文 QA / 引用准确率', '不同长度 PPL', 'TTFT by context'],
    tradeoff: '插值可低成本延长窗口，但可能损伤短距分辨率；继续训练更稳但增加数据和算力。',
    failures: ['只做单 needle 成功展示', '把最大窗口当有效窗口', '关键证据放中段后准确率突降'],
    review: ['训练长度和外推长度分别是多少？', 'needle 深度/干扰项怎么覆盖？', '短上下文能力是否回退？'],
    caseStudy: '合同审查从 16K 扩到 128K：设计长度×证据深度×干扰文档三维测试，并决定 RAG 与全量输入边界。',
  },
  {
    id: 'kv', no: 'L04', title: 'MHA / MQA / GQA 与 KV Cache', subtitle: '并发上限常被缓存而非参数卡住',
    formula: 'KV bytes = 2·L·T·Hkv·Dh·B·dtype_bytes',
    formulaNote: '2 表示 K 与 V；B 是并发序列数。MHA 的 Hkv=Hq，MQA 的 Hkv=1，GQA 介于两者。',
    architecture: 'Prefill 并行处理输入并写入 KV；decode 每步读取历史 KV 并新增一个位置，通常更受显存带宽与调度影响。',
    constraints: ['长上下文×并发线性吃显存', 'decode 的小矩阵计算利用率低', '量化 KV 需校准质量', '会话生命周期影响回收'],
    decision: '高并发服务优先评估 GQA/MQA、KV 量化与分页管理；长输入场景单独设 prefill 池和队列。',
    metrics: ['KV pool utilization', 'prefill/decode queue', 'TTFT / TPOT / ITL', 'OOM / eviction', 'tokens/s'],
    tradeoff: '更少 KV heads 显著省缓存，但可能损失质量；KV 低比特继续省显存，却增加量化误差和 kernel 复杂度。',
    failures: ['只按权重显存估机器', '平均长度正常但 p99 长会话 OOM', '把 TTFT 和 TPOT 混成总延迟'],
    review: ['峰值并发与长度联合分布？', 'KV 是否预留碎片和运行时空间？', 'prefill 会不会阻塞 decode？'],
    caseStudy: '32K 输入、1K 输出的报告服务：计算 GQA 与 MHA 的 KV 差异，并给出并发准入和降级策略。',
    practice: expertLLMPractices.kv,
  },
  {
    id: 'serving', no: 'L05', title: '高性能推理栈', subtitle: 'FlashAttention、PagedAttention 与连续批处理',
    formula: 'goodput = 满足 SLO 的有效 tokens / wall time；utilization ≠ goodput',
    formulaNote: 'FlashAttention 通过 IO-aware tiling 避免物化完整注意力矩阵；PagedAttention 管理非连续 KV 块；continuous batching 动态加入/退出请求。',
    architecture: '请求经过 admission、prefill、decode 调度与 KV block manager；吞吐优化必须同时约束 TTFT、TPOT 和 p95。',
    constraints: ['prefill/decode 资源争用', '请求长度差异造成 head-of-line blocking', '分页仍有块内碎片', '批越大单请求等待越久'],
    decision: '交互场景按 SLO 最大化 goodput，而非裸 TPS；离线任务可用更大 batch，并考虑 prefill/decode 解耦。',
    metrics: ['TTFT p50/p95', 'TPOT / ITL p95', 'request / token goodput', 'batch occupancy', 'KV cache hit'],
    tradeoff: '更激进批处理提高吞吐但拉高排队；prefix cache 降 prefill 成本但需要命中率、隔离和失效治理。',
    failures: ['GPU utilization 高但 SLO 大面积超时', '只报平均 TPS', '长请求饿死短请求或反向插队'],
    review: ['调度目标函数是什么？', 'prefix cache 如何做租户隔离？', '过载时拒绝、排队还是降级？'],
    caseStudy: '同时到达 100 个短对话与 2 个 100K 报告：制定优先级、chunked prefill 和 SLO 保护方案。',
    practice: expertLLMPractices.serving,
  },
  {
    id: 'compression', no: 'L06', title: '量化、蒸馏与推测解码', subtitle: '把成本优化拆成权重、行为与解码路径',
    formula: 'speedup_spec ≈ 1 / [(1−α)+α/k+overhead]（教学近似）',
    formulaNote: 'α 为草稿接受率、k 为一次验证 token 数。FP16/BF16 训练稳定性不同；INT8/INT4 主要减少权重带宽与显存。',
    architecture: '量化改变数值表示；蒸馏把教师行为迁移给学生；speculative decoding 用小草稿模型提议并由目标模型验证。',
    constraints: ['离群通道导致低比特误差', '校准集必须覆盖真实分布', '低 batch 才常显著受权重带宽限制', '接受率依赖任务与采样参数'],
    decision: '先按流量切片做质量-成本 Pareto：结构化/短答可尝试 INT4 或小模型蒸馏，高风险推理保留高精度。',
    metrics: ['tokens/$', 'acceptance rate', 'task delta by slice', '显存与功耗', 'TPOT p95'],
    tradeoff: '低比特降低成本但可能伤害长尾推理；蒸馏部署简单但受教师偏差；推测解码保留目标分布但系统更复杂。',
    failures: ['只测困惑度不测业务', '校准数据与线上语言不一致', '草稿太强导致成本抵消收益'],
    review: ['量化权重、激活还是 KV？', '哪类样本最先退化？', 'spec 接受率低时如何自动关闭？'],
    caseStudy: '预算要求 tokens/$ 提升 2×：比较 INT4、8B 蒸馏和 speculative 三条路线及回滚门槛。',
  },
  {
    id: 'alignment', no: 'L07', title: 'SFT、RLHF/PPO、DPO 与 GRPO', subtitle: '对齐目标不是一个“更好”分数',
    formula: 'DPO: −log σ(β[(logπθ(y⁺)−logπref(y⁺))−(logπθ(y⁻)−logπref(y⁻))])',
    formulaNote: 'SFT 拟合示范；PPO 优化奖励并受 KL 约束；DPO 直接使用偏好对；GRPO 用组内相对奖励降低对 value model 的依赖。',
    architecture: '数据 rubric、参考策略、奖励信号、采样策略与离线评估共同定义“被优化的行为”。不同方法不是线性升级关系。',
    constraints: ['偏好标注噪声和位置偏差', '在线 RL 成本和不稳定性', '奖励模型分布外失真', 'KL/β 过强或过弱'],
    decision: '先 SFT 建格式和能力；稳定偏好对且成本敏感用 DPO；可验证奖励和探索收益明确时再考虑 PPO/GRPO。',
    metrics: ['win rate with CI', 'KL to reference', 'reward / length correlation', '格式通过率', '能力回归切片'],
    tradeoff: 'RL 探索能力强但复杂；DPO 稳定便宜但受离线数据支持域限制；SFT 可控却难表达相对偏好。',
    failures: ['reward hacking', '长度偏差把啰嗦当优质', '模式坍缩与多样性下降', '安全提升伴随过度拒答'],
    review: ['奖励可被怎样投机？', 'reference 与 β 如何选？', '偏好是否按长度/风格消偏？'],
    caseStudy: '写作助手变得更长但用户完成率下降：定位 reward-length 相关，重做 pairwise rubric 与线上实验。',
  },
  {
    id: 'rag-agent', no: 'L08', title: 'RAG / Agent 生产架构', subtitle: '答案质量是多阶段乘积，不是单模型分数',
    formula: 'P(success) ≈ P(recall)·P(rerank|recall)·P(use evidence)·P(valid action)',
    formulaNote: '乘积仅用于故障预算直觉；阶段并非严格独立。端到端失败必须回溯到 chunk、索引、重排、拼装、生成或工具执行。',
    architecture: 'query rewrite → hybrid recall → rerank → context packing → grounded generation；Agent 再叠加 planner、tool protocol、state、termination 与审计。',
    constraints: ['chunk 边界破坏语义', '索引新鲜度与权限过滤', '上下文证据冲突', '工具副作用、超时与循环'],
    decision: '知识问答优先确定性 RAG 流水线；只有任务必须跨系统行动时才引入 Agent，并按工具风险分级授权。',
    metrics: ['Recall@k / NDCG', 'citation precision', 'groundedness', 'tool success/timeout', 'loop depth', 'trace completeness'],
    tradeoff: '更大 k 提升召回但增加噪声、token 与延迟；更自治的 Agent 提升覆盖但放大越权和不可预测性。',
    failures: ['召回相关但不支持结论', '上下文拼装截断关键证据', 'prompt injection 驱动越权工具', '无终止条件反复调用'],
    review: ['每阶段能否独立回放？', '工具协议是否幂等且最小权限？', '引用如何绑定到原文 span？'],
    caseStudy: '“退款政策”答错且引用看似正确：沿 trace 判断索引过时、rerank 错位还是生成未忠于证据。',
  },
  {
    id: 'evaluation', no: 'L09', title: '离线评估与线上实验', subtitle: '从 perplexity 到决策置信区间',
    formula: 'PPL=exp(−(1/T)Σ log p(xₜ|x<t)); CI≈p̂±1.96√[p̂(1−p̂)/n]',
    formulaNote: '二项比例 CI 为大样本近似；小样本或极端比例应使用 Wilson/Bootstrap。PPL 不可跨不同 tokenizer 直接比较。',
    architecture: '能力集、回归集、安全集、pairwise、人评与线上 A/B 形成分层证据；judge 模型必须校准一致性、偏置和版本。',
    constraints: ['评测污染与重复样本', 'judge 位置/长度/风格偏差', '人评一致性不足', '平均分掩盖高风险切片'],
    decision: '先定义最小可检测差异和失败成本，再决定样本量；上线闸门使用主指标+护栏+切片，而非单一总分。',
    metrics: ['task success / pass@k', 'pairwise win rate', 'Krippendorff α / κ', '置信区间', '安全事件率', '线上留存/完成率'],
    tradeoff: '自动评估快但偏差隐蔽；人评贴近业务但贵且波动；线上实验真实却承担用户风险。',
    failures: ['同一 judge 既产数据又评分', '无盲评导致品牌偏差', '统计显著但业务收益微小'],
    review: ['污染如何检测？', 'judge 与人评的一致性？', '切片最差值是否过闸？', '多重检验如何处理？'],
    caseStudy: '新版本总分 +2%，但代码用户 -8%：决定是否上线、如何设分流与补充样本。',
    practice: expertLLMPractices.evaluation,
  },
  {
    id: 'safety', no: 'L10', title: '安全、权限与故障治理', subtitle: '把“模型风险”拆成可检测、可阻断的系统事件',
    formula: 'Risk = likelihood × impact × exposure；residual risk = inherent risk − controls',
    formulaNote: '风险分数用于排序而非精确概率。安全体系应同时覆盖输入、上下文、模型输出、工具权限和数据出站。',
    architecture: '输入分类与隔离 → 检索权限过滤 → 模型策略 → 工具 policy enforcement → 输出 DLP/事实核验 → 审计与响应。',
    constraints: ['prompt injection 不能仅靠提示词解决', '多租户数据隔离', '拒答与可用性冲突', '异步工具副作用难回滚'],
    decision: '高影响动作采用 allowlist、参数校验、人工确认和幂等回滚；未知输入默认不获得额外权限。',
    metrics: ['hallucination / unsupported claim', 'injection ASR', 'unauthorized tool attempts', 'DLP hits', 'over-refusal rate', 'MTTR'],
    tradeoff: '更严格策略降低风险但增加拒答与延迟；更自治提高完成率但扩大暴露面和事故影响。',
    failures: ['把外部文档当可信指令', '模型自行决定权限', '日志记录了敏感原文', '安全升级后正常请求大面积拒答'],
    review: ['信任边界画在哪里？', '谁能批准高风险工具？', '事故能否定位到 prompt/证据/工具版本？'],
    caseStudy: '网页内容注入“导出所有客户”：推演检索隔离、指令优先级、工具授权、DLP 和告警链路。',
    practice: expertLLMPractices.safety,
  },
]

export const expertImageModules: ExpertModule[] = [
  {
    id: 'vae', no: 'I01', title: 'VAE 与潜空间信息瓶颈', subtitle: '压缩率决定算力，也决定可恢复细节',
    formula: 'L = λrec‖x−x̂‖ + λperc·LPIPS(x,x̂) + β·DKL(q(z|x)‖p(z))',
    formulaNote: '像素重建、感知损失与 KL 权重共同决定可重建性和潜空间规整性；空间压缩 f×f 使 token/特征面积约降为 1/f²。',
    architecture: '编码器把像素压到 latent，生成主干在 latent 中建模，解码器恢复图像。VAE 是生产质量上限的一部分而非透明压缩器。',
    constraints: ['高压缩损失文字和高频纹理', 'KL 过强导致信息不足', '解码器色偏/棋盘格', '高分辨率解码显存峰值'],
    decision: '商品细节、文字与人脸修复场景需单独评估 VAE；不要只用生成主干指标替代端到端重建测试。',
    metrics: ['PSNR / SSIM', 'LPIPS', 'OCR accuracy', 'face identity similarity', 'decode latency'],
    tradeoff: '更高压缩显著降主干算力，但牺牲局部可逆性；感知损失提高清晰感却可能“补造”纹理。',
    failures: ['把 VAE 伪影误判为采样器问题', '平均 LPIPS 好但文字全错', '只测自然图不测业务素材'],
    review: ['空间/通道压缩率？', '哪类细节不可逆？', 'VAE 是否与主干联合版本管理？'],
    caseStudy: '海报生成文字边缘发糊：区分文本渲染、latent 分辨率与 VAE 重建瓶颈。',
  },
  {
    id: 'dit', no: 'I02', title: 'U-Net vs DiT', subtitle: '卷积多尺度归纳偏置与 token 扩展路线',
    formula: 'Ntokens=(H/fp)·(W/fp)；self-attention FLOPs ∝ Ntokens²·d',
    formulaNote: 'fp 是 latent patch 尺寸。DiT 将 latent patch 化为 token；分辨率或更小 patch 会快速增加 token 与注意力成本。',
    architecture: 'U-Net 通过卷积、下采样/上采样和 skip connection 处理多尺度；DiT 用 Transformer block 提供更规整的 scaling 路径。',
    constraints: ['DiT 高分辨率 token 二次成本', 'U-Net kernel/结构复杂', 'patch 太大损细节', '多宽高比 batch 利用率'],
    decision: '不要用架构名替代压测；按目标分辨率、控制接口、训练规模与已有生态选择。',
    metrics: ['FLOPs / image', 'step latency', '显存峰值', 'scaling curve', '细节/构图切片'],
    tradeoff: 'DiT 易随规模扩展但依赖数据/算力；U-Net 多尺度效率成熟但全局建模和扩展形态更复杂。',
    failures: ['把 token 数当像素数', '训练分辨率外直接放大', '只比参数不比激活和步耗时'],
    review: ['latent 与 patch 各多大？', '不同宽高比如何打包？', '高分辨率是原生还是二阶段？'],
    caseStudy: '从 1024 升到 2048：估算 token 与 attention 增幅，并决定原生生成还是 upscaler。',
  },
  {
    id: 'targets', no: 'I03', title: '预测目标、SNR 与噪声调度', subtitle: '不同时间步学到的不是同一种难度',
    formula: 'xₜ=αₜx₀+σₜε；SNR(t)=αₜ²/σₜ²；v=αₜε−σₜx₀',
    formulaNote: 'ε-pred、x0-pred、v-pred 可相互换算但优化权重不同；loss weighting 决定模型更关注高噪声结构还是低噪声细节。',
    architecture: 'noise schedule 定义训练路径，prediction target 定义监督信号，SNR/min-SNR weighting 平衡时间步梯度。',
    constraints: ['高/低 SNR 梯度尺度差异', '训练目标与 sampler 参数化需兼容', 'schedule 改动影响全程分布'],
    decision: '质量问题应按时间步/频段定位，不要只调 steps；迁移 sampler 前先确认模型的 prediction type。',
    metrics: ['loss by timestep/SNR', 'gradient norm', '低步数质量曲线', '高频细节与结构切片'],
    tradeoff: '强调高噪声利于全局结构，强调低噪声利于细节；不平衡会让某一端学习不足。',
    failures: ['prediction type 配错导致整图异常', '平均 loss 掩盖时间步坏点', 'schedule 与推理步表错配'],
    review: ['loss 如何按 SNR 加权？', '验证是否覆盖不同步数？', '目标变更后哪些 sampler 仍兼容？'],
    caseStudy: '低步数构图稳定但细节糊：判断是 solver、低 SNR 学习还是 VAE 问题。',
  },
  {
    id: 'samplers', no: 'I04', title: 'Sampler 与高速生成', subtitle: 'DDPM、DDIM、Euler、DPM-Solver 到 Flow',
    formula: 'ODE: dx/dt=fθ(x,t)；Euler: xₜ₋Δ=xₜ−Δ·fθ(xₜ,t)',
    formulaNote: 'DDPM 常含随机性；DDIM 可走确定性路径；Euler 是一阶数值法；DPM-Solver 利用扩散 ODE 结构做高阶更新。',
    architecture: '采样器是对学习到的向量场/score 的数值积分。Flow Matching/Rectified Flow 学习从噪声到数据的速度场，追求更直路径。',
    constraints: ['高阶方法并非所有低步数都稳', '随机性影响多样性和复现', '模型训练参数化限制 solver', '每步成本不完全相同'],
    decision: '以步数×单步耗时×有效图率比较，不用“某 sampler 最好”的静态结论；为生产固定完整配置。',
    metrics: ['latency / image', 'effective yield', 'quality-vs-steps AUC', 'seed stability', 'artifact rate'],
    tradeoff: '少步更快但误差大；确定性利于复现但可能降低探索；高阶 solver 单步更复杂却可减少步数。',
    failures: ['盲目加步数却无质量收益', '切 sampler 后 seed 不可比', '低步数出现边缘破碎与构图漂移'],
    review: ['比较的是 NFE 还是 steps？', '单步耗时是否一致？', '失败图是否计入单位有效成本？'],
    caseStudy: '延迟从 4s 压到 1s：比较 30-step Euler、12-step DPM-Solver 与蒸馏模型的有效图成本。',
  },
  {
    id: 'cfg', no: 'I05', title: 'CFG 与条件控制', subtitle: '遵循度不是无限增益旋钮',
    formula: 'ε̂=εu+s(εc−εu)',
    formulaNote: 's 放大有条件与无条件预测差。过高 guidance 会将样本推向分布边缘，引起过饱和、纹理烧焦与多样性损失。',
    architecture: '文本通过 Cross Attention 注入；CFG 在采样时调节条件方向。结构、身份和风格等强约束通常需要额外适配器。',
    constraints: ['高 CFG 可能需双分支计算', '长提示属性绑定错位', '不同模型舒适区不同', '负向条件相互冲突'],
    decision: '把 CFG 与 prompt adherence、审美和多样性联合扫参；组合条件时分别设权重并记录版本。',
    metrics: ['prompt adherence', 'saturation / artifact rate', 'pairwise aesthetic', 'diversity / LPIPS'],
    tradeoff: '高 CFG 提升表面遵循但降低自然度和多样性；低 CFG 更自由但漏条件。',
    failures: ['过饱和和硬轮廓', '多主体属性串位', '以负向提示代替安全检测'],
    review: ['CFG sweep 的 Pareto 点？', '关键约束能否转结构输入？', '多条件权重如何校准？'],
    caseStudy: '品牌色遵循提升但人像肤色失真：调整 CFG、区域控制与后验色彩检查。',
  },
  {
    id: 'control', no: 'I06', title: 'ControlNet、IP-Adapter、LoRA 与 DreamBooth', subtitle: '结构、参考、权重资产各控制不同对象',
    formula: 'LoRA: W′=W+BA；rank(B A)=r≪d',
    formulaNote: 'ControlNet 注入边缘/深度/姿态等空间条件；IP-Adapter 注入图像提示特征；LoRA/DreamBooth 通过训练改变权重行为。',
    architecture: 'Cross Attention 负责文本条件；ControlNet 锁结构；IP-Adapter 传参考图语义/身份；LoRA 轻量沉淀风格/主体；DreamBooth 做更重的个性化。',
    constraints: ['训练数据授权与清洗', '身份过拟合/背景泄漏', '多 adapter 冲突', '控制模型与 base 版本兼容'],
    decision: '姿态用 ControlNet，参考身份用 IP-Adapter，低成本风格资产用 LoRA；高一致身份再评估 DreamBooth，并常组合 img2img/inpaint。',
    metrics: ['identity similarity', 'pose / edge adherence', 'style leakage', 'train GPU-hours', 'effective yield'],
    tradeoff: '零训练适配器上线快但上限有限；LoRA 成本低但需数据；DreamBooth 一致性强却更贵且易过拟合。',
    failures: ['把风格 LoRA 当姿态控制', '主体身份与训练背景绑定', '叠加控制导致僵硬或崩坏'],
    review: ['控制对象到底是结构、身份还是风格？', '数据量和授权？', 'base 升级如何回归？'],
    caseStudy: '6 张人物参考图制作连续分镜：组合 IP-Adapter、姿态 ControlNet、LoRA 和局部重绘。',
  },
  {
    id: 'flow', no: 'I07', title: 'Flow Matching、Consistency 与蒸馏', subtitle: '更直的路径、更少的函数评估',
    formula: 'Flow Matching: dx/dt=vθ(x,t)；Consistency: f(xₜ,t)≈f(xₛ,s)',
    formulaNote: 'Rectified Flow 追求更直输运路径；Consistency 模型让不同噪声点映射到一致结果；蒸馏将多步教师压到少步学生。',
    architecture: '高速路线可来自更易积分的向量场、跨时间一致性训练或教师轨迹蒸馏；三者的数据和误差来源不同。',
    constraints: ['少步学生容量与教师误差', '蒸馏数据覆盖', '一步生成多样性下降', '再训练与版本维护成本'],
    decision: '大规模低延迟业务可投资蒸馏；需求多变或长尾质量优先时保留多步基线作为 fallback。',
    metrics: ['NFE', 'latency p95', 'teacher-student gap', 'diversity', 'failure slice regression'],
    tradeoff: '少步显著降延迟，但通常牺牲细节、多样性或可编辑空间；蒸馏把推理成本转移到训练。',
    failures: ['只展示均值，忽略少步灾难样本', '学生复制教师偏差', '版本升级需重新蒸馏'],
    review: ['收益来自路径还是蒸馏？', '教师成本如何摊销？', '哪些请求回退到多步？'],
    caseStudy: '头像服务目标 p95<800ms：设计 4-step 主链与 20-step 高质量回退的路由条件。',
  },
  {
    id: 'image-eval', no: 'I08', title: '图文生成生产评估', subtitle: '单一 FID 无法回答产品是否可用',
    formula: '单位有效图成本=(生成+重试+审核+后处理成本)/通过数',
    formulaNote: 'FID 衡量分布特征差异，不适合单图评分；CLIPScore 近似图文相关；LPIPS 衡量感知差异，三者都不能替代业务人评。',
    architecture: '评测集按 prompt adherence、composition、identity、text rendering、aesthetic、diversity、安全、延迟与成本分层。',
    constraints: ['审美主观与人群差异', '指标可被风格投机', '成功样本挑选偏差', '安全长尾低频高损'],
    decision: '上线闸门使用有效图率、关键切片和成本护栏；对文字、身份等硬约束用专门检测器。',
    metrics: ['CLIPScore / VQA', 'FID/KID（集合级）', 'LPIPS diversity', 'OCR exact match', 'identity', 'p95 / cost'],
    tradeoff: '多候选提高通过率却增加成本；严格过滤提高安全但增加误杀和延迟。',
    failures: ['只看 FID', '不把重试算成本', '身份均值合格但某人群漂移严重'],
    review: ['通过率分母包含失败图吗？', '自动指标与人评相关性？', '安全与审美是否独立评审？'],
    caseStudy: '新模型 CLIPScore 更高但设计师采用率下降：检查构图、文字和多样性切片。',
    practice: expertImagePractices['image-eval'],
  },
  {
    id: 'pipeline', no: 'I09', title: '多阶段图像生产系统', subtitle: '质量来自 planner 到 safety 的整条链路',
    formula: 'E2E yield = Π stage pass rate（独立近似）；E2E latency = Σ stage latency + queue',
    formulaNote: '阶段通过率并不严格独立，但乘积可暴露“每阶段 95% 最终只剩多少”的风险。并行候选会改变延迟与成本结构。',
    architecture: 'prompt rewrite → planner/layout → base model → refiner/inpaint → upscaler → OCR/identity/safety checker → asset trace。',
    constraints: ['阶段版本耦合', '错误在后段放大', '中间资产存储与隐私', '重试风暴与尾延迟'],
    decision: '能用确定性排版完成的文字不要强迫 base model 生成；按失败 taxonomy 将重试定向到具体阶段。',
    metrics: ['stage pass/fallback rate', 'trace ID coverage', 'retry depth', 'queue p95', 'unit effective cost', 'safety leak'],
    tradeoff: '更多阶段提升可控性和检测能力，但增加延迟、成本、运维与版本组合。',
    failures: ['rewrite 改变用户意图', 'refiner 修坏身份', 'upscaler 虚构纹理', 'safety checker 误杀特定风格'],
    review: ['每阶段输入输出可否回放？', '谁拥有最终 prompt？', '失败应重试哪一段而非整链？'],
    caseStudy: 'AI 创作助手文字错误且延迟高：拆分文字排版、局部修复和按阶段缓存，形成上线架构。',
    practice: expertImagePractices.pipeline,
  },
]
